name: C++ Build & Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        run: docker build -t cpp-container .

  make:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        run: docker run -t cpp-container
  lint:
    needs: make
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker run -t cpp-container cpplint *.cpp *.h
